### ISSUE TITLE
eden-parent 未发布到中央仓库

### ISSUE THREAD

**Issue by I-Love-China** [shiyindaxiaojie/eden-demo-layer#6]
您好，构建报错 `Could not find artifact org.ylzl:eden-parent:pom:2.4.13-SNAPSHOT`，请问在哪个仓库能获取到这个依赖 ？

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/41012300/195770341-1f12b39b-f56e-40e9-97c6-a7c69cfd45da.png">

**Comment by shiyindaxiaojie** [comment]
https://github.com/shiyindaxiaojie/eden-architect，暂时没有发布到 Maven 中央仓库。

**Comment by I-Love-China** [comment]
谢谢
